In [11]:
%reload_ext autoreload
%autoreload 2

In [12]:
from backtester.backtester import sample_polars_spot, sample_polars_rate, sample_polars_option, MarketDataProvider

In [13]:
lf_rate = sample_polars_rate()
lf_spot = sample_polars_spot()
lf_option = sample_polars_option()
lf_rate.show()
lf_spot.show()
lf_option.show()

time_start,time_end,rate
"datetime[μs, UTC]","datetime[μs, UTC]",f64

time_start,time_end,exchange,base,quote,px_bid,px_ask,px_mark
"datetime[μs, UTC]","datetime[μs, UTC]",str,str,str,f64,f64,f64

time_start,time_end,exchange,base,quote,strike,expiry,kind,iv_bid,iv_ask,iv_mark
"datetime[μs, UTC]","datetime[μs, UTC]",str,str,str,f64,"datetime[μs, UTC]",str,f64,f64,f64

In [14]:
mdp = MarketDataProvider(lf_rate, lf_spot, lf_option)
mdp

In [18]:
mdp.table_priced.collect_schema()

Schema([('time_start', Datetime(time_unit='us', time_zone='UTC')),
        ('time_end', Datetime(time_unit='us', time_zone='UTC')),
        ('exchange_option', String),
        ('base_option', String),
        ('quote_option', String),
        ('strike', Float64),
        ('expiry', Datetime(time_unit='us', time_zone='UTC')),
        ('kind', String),
        ('iv_bid', Float64),
        ('iv_ask', Float64),
        ('iv_mark', Float64),
        ('exchange_spot', String),
        ('base_spot', String),
        ('quote_spot', String),
        ('px_bid_spot', Float64),
        ('px_ask_spot', Float64),
        ('px_mark_spot', Float64),
        ('rate', Float64),
        ('px_bid_option', Float64),
        ('px_ask_option', Float64),
        ('px_mark_option', Float64),
        ('delta', Float64),
        ('gamma', Float64),
        ('vega', Float64),
        ('theta', Float64),
        ('rho', Float64)])